name: wordbridge
description: "Free, open-source AAC with customizable motor planning."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  archive: ^4.2.0
  crypto: ^3.0.7
  drift: ^2.34.3
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2
  flutter_secure_storage: ^11.0.0
  flutter_svg: ^2.3.0
  flutter_tts: ^4.2.5
  go_router: ^18.0.0
  http: ^1.6.0
  image: ^4.9.2
  image_picker: ^1.2.3
  path: ^1.9.1
  path_provider: ^2.1.6
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.34.5
  build_runner: ^2.16.0

flutter:
  uses-material-design: true

  assets:
    - assets/symbols/core/
